config/routes.rb
Rails.application.routes.draw do
  root 'users#home'

  get 'login' => 'sessions#new', as: 'new_session'
  post 'login' => "sessions#create"
  get 'logout' => 'sessions#destroy'


  get 'user_profile/:id' => 'profiles#show', as: 'user_profile'
  get 'user_profile/:id/edit' => 'profiles#edit', as: 'edit_profile'
  patch 'user_profile/:id/edit' => 'profiles#update'
  resources :users do
    resources :profiles
  end
  resources :conversations do
    resources :messages
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
 where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end


end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  after_create :create_user_profile
  serialize :interests, Array
  validates :username, presence: true
  validates :password, length: {minimum: 8}
  has_secure_password

  has_many :conversations, :foreign_key => :sender_id

  def create_user_profile
    Profile.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
 before_action :authenticate_user
 def index
   @users = User.all
   @conversations = Conversation.all
 end
 def create
   if Conversation.between(params[:sender_id],params[:recipient_id])
     .present?
    @conversation = Conversation.between(params[:sender_id],
     params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    @message = @conversation.messages.new
  end


def new
 @message = @conversation.messages.new
end

def create
 @message = @conversation.messages.new(message_params)
 if @message.save
  redirect_to conversation_messages_path(@conversation)
 end
end


private

 def message_params
  params.require(:message).permit(:body, :user_id)
 end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
      @profile = Profile.new
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def show
    @profile = Profile.find(params[:id])
    if @profile.name == nil
      redirect_to edit_profile_path
    end
  end

  def create
    new_profile = Profile.new(profile_params)
    new_profile.save
    session[:profile_id] = new_profile.id
    redirect_to profile_path new_profile
  end

  def update
    profile = Profile.find_by(user_id: current_user.id)
    profile.update(profile_params)
    profile.save
    redirect_to user_profile_path(profile)
  end

  def destroy
    Profile.find(params[:id]).destroy
    redirect_to profiles_path
  end

  def index
    @profiles=Profile.all
  end

  private

  def profile_params

    params.require(:profile).permit(:name, :about)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: session_params[:username])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

    new_user = User.new(user_params)
    new_user.save
    session[:user_id] = new_user.id
    redirect_to user_path new_user

  end
  def home
  end 
  def edit
    @user. User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    user.save
    redirect_to user_path user
  end


  def delete
  end

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])

    #@profile = @user.profiles

  end

  private

  def user_params

    params.require(:user).permit(:username, :password, :about, :age, :location, :interests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
  def authenticate_user
    if !current_user
      redirect_to new_session_path, notice: "You must be signed in to do that!"
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>

  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
      <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <%= link_to recipient.username, conversation_messages_path(conversation) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="ui segment">
  <h3>All Users</h3>
    <div class="ui list">
      <% @users.each do |user| %>
        <% if user.id != current_user.id %>
          <div class="item">
            <%= user.username %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HailDatinV3</title>





    <%= csrf_meta_tags %>



    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
    table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 50%%; }
    td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
    }

    tr:nth-child(even) {
    background-color: #dddddd;
    }
    </style>

    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>

  </head>

  <body>
    <%= yield %>





          <!-- <i class="home icon"></i><%= link_to "Home", root_path, class: "item" %>
            <% if current_user %>
              <%= link_to "Mailbox", conversations_path, class: "item" %>
              <div class="right menu">
                <%= link_to 'Sign Out', logout_path, class: "item" %>
              </div>
            <% else %>
              <div class="right menu">
                <%= link_to 'Sign Up', new_user_path, class: "item" %>
                <%= link_to "Sign-In", login_path, class: "item" %>
              </div>
            <% end %> -->
        <!-- </div> -->

  </body>
</html>

app/views/messages/index.html.erb
<% if @over_ten %>
 <%= link_to 'Show Previous', '?m=all' %>
<% end %>
<div class="ui segment">
 <% @messages.each do |message| %>
  <% if message.body %>
   <% user = User.find(message.user_id) %>
   <div class="item">
    <div class="content">
     <div class="header"><strong><%= user.username %></strong> <%= message.message_time %></div>
      <div class="list">
       <div class="item">
        <i class="right triangle icon"></i>
         <%= message.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>
<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
 <div class="field">
   <%= f.text_area :body, class: "form-control" %>
 </div>
 <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
 <div>
   <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
 </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>


<%= form_for @profile, { url: {controller: 'profiles', action: "update"} } do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name %><br>
  <%= f.label :about %>
  <%= f.text_field :about %><br>
  <%= f.submit %>
<% end %>

app/views/profiles/show.html.erb
<h2>One specific profile</h2>

<h3><%= @profile.name %> by: <%= @profile.user.username %></h3>


<%= link_to 'édit profile', edit_profile_path %>
<%= @profile.name %>
<%= @profile.about %>

app/views/users/_profileform.html.erb
<%= form_for @user do |f| %>
<%= f.label :about %>
<%= f.text_area :about %>

<%= f.label :age %>
<%= f.text_field :age %>

<%= f.label :location %>
<%= f.text_area :location %>

<%= f.label :interests %>
<%= f.text_area :interests %>
<% end %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/home.html.erb
<div class="jumbotron col-lg-10 offset-2">
  <h1 class="display-3">Hail Datin'</h1>
  <p class="lead">The world's favorite heavy metal dating site.</p>
  <p>Find your fallen angel today!</p>
  <p class="lead">
    <a class="button_example btn-primary btn-lg" href="users/new" role="button">Register</a>
    <a class="button_example btn-primary btn-lg" href="login" role="button">Sign In</a>
  </p>
</div>





<%= image_tag("HomeLogo1.png", alt: "HomeLogo1", class: "HomeLogo1") %>

app/views/users/index.html.erb
<h1>Users</h1>
<p>All the users</p>

  <table style="width:100%">
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Interests</th>
    </tr>
  <%= @users.each do |user| %>
  <tr>
    <td> <%= link_to user.username, user_path(user.id)  %> </td>
    <td><%= user.password %> </td>
     <% @interests = user.interest.split("").select{|char| ('abcdefghijklmnopqrstuvwxyz').include?(char.downcase) || (" ").include?(char)}.join("").split(" ") %>
     <td> <% @interests.each do |interest|  %>
    <%= interest %>, <% end %></td>
  </tr>
  <% end  %>

</table>

app/views/users/new.html.erb
<div class="registrationhail">
Hail
</div>

<div class="registrationdatin">
Datin'
</div>

<h2>Sign Up Homie!</h2>

<div class="registration">
  <%= form_for @user do |f| %>
    <%= f.label :username  %>
    <%= f.text_field :username, placeholder: "Choose a Username" %><br>
    <%= f.label :password %>
    <%= f.text_field :password, placeholder: "Password" %><br>
    <%= f.submit %>
  <% end %>
</div>
<%= image_tag("HomeLogo1.png", alt: "HomeLogo1", class: "RegistrationLogo") %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>show</title>
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <%= image_tag("HomeLogo1.png", alt: "HomeLogo1", class: "navlogo") %>
      <%= image_tag("HomeLogo1.png", alt: "HomeLogo1", class: "navlogo2") %>
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Hail Datin'</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">View Profile</a></li>
              <li><a href="#">Edit Profile</a></li>
              <li><a href="#">Account Settings</a></li>
            </ul>
          </li>
          <li class="signout" style="float:right;"><a href="#">Sign Out</a></li>
          <form class="navbar-form navbar-left" action="/action_page.php">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search Metalheads" name="search">
          </div>
          <button type="submit" class="btn btn-default">Rock On!</button>
        </ul>
      </div>
    </nav>

  </body>
</html>






























<!-- <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <span class="navbar-toggler-icon"></span>

  </button>
  <a class="navbar-brand" href="#">Hail Datin'</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <i class="homeicon"></i>
    <%= link_to "Home", root_path, class: "item" %>

      <% if current_user %>
        <%= link_to "Mailbox", conversations_path, class: "item" %>
        <div class="right menu">
          <%= link_to 'Sign Out', logout_path, class: "item" %>
        </div>
      <% else %>
        <div class="rightmenu">
          <%= link_to 'Sign Up', new_user_path, class: "item" %>
          <%= link_to "Sign-In", login_path, class: "item" %>
        </div>
      <% end %>

  </div>

  <% if current_user %>
  <p>Welcome, <div class="dropdown">
              <button class="dropbtn"><%=current_user.username%></button>
              <div class="dropdown-content">
                  <a href="#">View Profile</a>
                  <%= link_to "Sign-In", new_user_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"} %>
                  <a href="#">Account Settings</a>
                </div>
              </div> </p> -->




<!-- keep commented out -->
              <!-- <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Action <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "link1", "#",{:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></li>
        <li><%= link_to "link1", "#",{:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></li>
        <li><%= link_to "link3", "#",{:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></li>
        <li class="divider"></li>
        <li><%= link_to "link4", "#",{:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %></li>
      </ul>
    </div> -->





  <!-- <% else %>
  <% link_to "Login", new_session_path %>
  <% end %> -->








  <%= yield %>
</nav>

<h1>Users#show</h1>
<h2><%= @user.username %></h2>
<p>Date Registered: <%= @user.created_at %></p>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/userprofile.html.erb
<% render 'profileform', { url: {controller: 'users', action: "create"} } %>